'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-webgl']});
try{const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.OBTP_BASE_URL||'http://127.0.0.1:8765/');const v3=page.frameLocator('#v3'),v2=page.frameLocator('#v2');
assert.equal(await page.locator('html').getAttribute('lang'),'lt');await page.locator('#language').selectOption('en');
async function choose(id,value){await v3.locator('#'+id+' + .choice-row [data-value="'+value+'"]').click();}
async function ready(){await v3.locator('#status').filter({hasText:/Your sauna preview|Jūsų pirties peržiūra|Your studio preview|Jūsų studijos peržiūra/}).waitFor({timeout:60000});}
await ready();
assert.equal(await page.locator('iframe:not([hidden])').getAttribute('id'),'v3');
assert.deepEqual(await v3.locator('#studio-version option').evaluateAll(xs=>xs.map(x=>x.value)),['v2','v3']);
assert.equal(await v3.locator('#preset option').count(),2);assert.match(await page.locator('#customer-product').textContent(),/Module type/);
assert.equal(await v3.locator('#terrace-depth').inputValue(),'1200');assert.equal(await v3.locator('#window-width').inputValue(),'1180');
assert.equal(await v3.locator('#facade option').count(),1);
assert(!(await v3.locator('#component-details').evaluate(x=>x.open)));assert(!(await v3.locator('#technical-notes').evaluate(x=>x.open)));
assert.equal(await v3.locator('#assembly-system').inputValue(),'0');assert(await v3.locator('#assembly-system option[value="1"]').isDisabled());
const initial=await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.source_geometry_sha256);
for(const size of ['s','m','l']){await choose('sauna-size',size);await ready();assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.selection.size),size);await page.screenshot({path:`studio-sauna-${size}.png`,fullPage:true});}
await choose('sauna-storage','true');await ready();assert(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.config.storage));
for(const width of ['580','880','1180']){await choose('window-width',width);await ready();assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.config.window_width),Number(width));}
assert.equal(await v3.locator('#terrace-depth option').count(),1);assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.config.terrace_steps),2);
for(const roof of ['0','1','2']){await choose('sauna-roof',roof);await ready();assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.config.roof_type),Number(roof));}
await v3.locator('[data-view="cut"]').click();assert(!(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.renderer.items.some(x=>['roof','ceiling'].includes(x.stage)))));
assert(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.renderer.items.some(x=>x.stage==='interior')));
const angle=await v3.locator('canvas').evaluate(()=>OBTPStudioV3.renderer.angle);await v3.locator('#rotate').click();assert(Math.abs(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.renderer.angle)-(angle+Math.PI/2))<1e-9);
await v3.locator('#reset').click();await page.screenshot({path:'studio-sauna-panels-cut.png',fullPage:true});
await choose('sauna-size','m');await ready();await choose('sauna-storage','false');await ready();await choose('sauna-roof','1');await ready();await choose('terrace-depth','1200');await ready();
assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.source_geometry_sha256),initial);
await page.locator('#customer-info').click();assert(await v3.locator('#customer-information').isVisible());await v3.locator('#supplier-information summary').click();assert((await v3.locator('#supplier-information .supplier-row').count())>=5);for(const img of await v3.locator('#supplier-information img').all())assert(await img.evaluate(async x=>{await x.decode();return x.naturalWidth>0;}));await page.screenshot({path:'studio-r06-suppliers.png',fullPage:true});
await v3.locator('#component-details summary').click();assert(await v3.locator('#schedule tr').count()>0);
assert.match(await v3.locator('#wood-total').textContent(),/Modeled wood: \d+[.]\d{3} m³/);
await page.locator('#customer-config').click();assert(await v3.locator('#configurator').isVisible());
await page.locator('#customer-config').click();await v3.locator('#studio-version').selectOption('v2');await v2.locator('#status').filter({hasText:/component instances · ready/}).waitFor();assert(await v2.locator('#bays').isVisible());await v2.locator('#studio-version').selectOption('v3');await page.locator('#customer-config').click();await ready();
await page.setViewportSize({width:390,height:844});assert(!(await v3.locator('#configuration-panel').isVisible()));await v3.locator('#mobile-config-toggle').click();assert(await v3.locator('#configuration-panel').isVisible());assert.equal(await v3.locator('#mobile-config-toggle').getAttribute('aria-expanded'),'true');await choose('window-width','880');await ready();await page.screenshot({path:'studio-r05-mobile-overlay.png',fullPage:true});await v3.locator('#mobile-config-toggle').click();assert(!(await v3.locator('#configuration-panel').isVisible()));assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.config.window_width),880);await v3.locator('#mobile-config-toggle').click();await choose('window-width','1180');await ready();await page.keyboard.press('Escape');assert.equal(await v3.locator('#mobile-config-toggle').getAttribute('aria-expanded'),'false');await v3.locator('[data-view="solved"]').click();await v3.locator('#solved-plan').evaluate(img=>img.decode());assert(await v3.locator('#solved-scroll').evaluate(x=>x.scrollWidth<=x.clientWidth && x.scrollHeight<=x.clientHeight));assert(await v3.locator('body').evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'studio-sauna-plan-mobile.png',fullPage:true});
await page.locator('#language').selectOption('lt');assert.equal(await v3.locator('html').getAttribute('lang'),'lt');assert.match(await v3.locator('h1').first().textContent(),/Susikurkite savo pirtį/);await page.locator('#customer-info').click();assert.match(await v3.locator('#customer-information h1').textContent(),/Techninė informacija/);await page.locator('#customer-config').click();assert.equal(await v3.locator('#window-width').inputValue(),'1180');await v3.locator('[data-view="3d"]').click();await page.screenshot({path:'studio-customer-lt-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'studio-customer-lt.png',fullPage:true});await page.locator('#customer-info').click();await page.screenshot({path:'studio-information-lt.png',fullPage:true});
await page.locator('#customer-drawings').click();assert(await v3.locator('#customer-drawings').isVisible());assert.equal(await v3.locator('#pdf-preview, #customer-drawings iframe, #pdf-open').count(),0);const pdfURL=await v3.locator('#pdf-download').getAttribute('href');const pdfResponse=await page.request.get(new URL(pdfURL,new URL('v3/',page.url())).href);assert(pdfResponse.ok());assert((await pdfResponse.body()).subarray(0,4).toString()==='%PDF');await page.screenshot({path:'studio-r04-drawings.png',fullPage:true});await page.locator('#customer-config').click();assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.renderer.arctic),true);await v3.locator('#appearance').selectOption('materials');assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.renderer.arctic),false);await v3.locator('#appearance').selectOption('arctic');await page.locator('#customer-product').click();assert.equal(await v3.locator('.photo-empty').count(),3);await page.screenshot({path:'studio-r04-gallery.png',fullPage:true});await page.locator('#customer-config').click();await page.screenshot({path:'studio-r04-customer.png',fullPage:true});await choose('sauna-roof','2');await ready();assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.metrics.height_mm),4480);await page.screenshot({path:'studio-r04-gable.png',fullPage:true});await v3.locator('#preset').selectOption('studio');await ready();
assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.config.program_type),1);
for(const size of ['s','m','l']){await choose('sauna-size',size);await ready();assert(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.metrics.building_area_bound_m2<=50));}
await v3.locator('[data-view="cut"]').click();await page.screenshot({path:'studio-r07-creative-cut.png',fullPage:true});
await v3.locator('[data-view="solved"]').click();await v3.locator('#solved-plan').evaluate(x=>x.decode());await page.screenshot({path:'studio-r07-creative-plan.png',fullPage:true});
await choose('sauna-storage','true');await ready();assert(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.config.storage));
await page.locator('#customer-drawings').click();assert.match(await v3.locator('#pdf-download').getAttribute('href'),/studio-l-storage/);const studioPDF=await page.request.get(new URL(await v3.locator('#pdf-download').getAttribute('href'),new URL('v3/',page.url())).href);assert(studioPDF.ok());
await page.locator('#customer-config').click();await v3.locator('[data-view="3d"]').click();await choose('sauna-roof','1');await ready();await page.screenshot({path:'studio-r07-creative.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await v3.locator('#mobile-config-toggle').click();assert(await v3.locator('#preset').isVisible());await page.screenshot({path:'studio-r07-creative-mobile.png',fullPage:true});await v3.locator('#preset').selectOption('sauna');await ready();await page.keyboard.press('Escape');
assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.scene.config.program_type),0);
assert.match(await v3.locator('h1').first().textContent(),/Susikurkite savo pirtį/);
assert.deepEqual(errors,[]);console.log('PASS: R04 exported-model defaults, all buyer controls, source identity roundtrip, cut, locked camera, wood, reference plans, mobile and WikiHouse version');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
