const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-webgl']});
try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.OBTP_BASE_URL || 'http://127.0.0.1:8765/'));
const v2=page.frameLocator('#v2');await v2.locator('#status').filter({hasText:'28 component instances · ready'}).waitFor();
assert.equal(await v2.locator('#schedule tr').count(),4);
assert.match(await page.locator('#v2').getAttribute('src'), /[?]build=[a-f0-9]{40}$/);
assert.equal(await v2.locator('label[for="bays"]').textContent(),'Number of modules');
assert(await v2.locator('#bays').isVisible());
assert.match(await v2.locator('script[src*="app.js"]').getAttribute('src'), /[?]build=[a-f0-9]{40}$/);
await v2.locator('#layer').selectOption('floor');await v2.locator('#status').filter({hasText:'1 component instances · ready'}).waitFor();
await page.locator('summary').click();await page.locator('[data-version="v1"]').click();
const v1=page.frameLocator('#v1');await v1.locator('#part-count').filter({hasText:/\d/}).waitFor();assert.ok(await v1.locator('#scene polygon').count()>0);
await v1.locator('#workroom').click();const size=await v1.locator('#model-size').textContent();
await page.locator('summary').click();await page.locator('[data-version="v2"]').click();assert.equal(await v2.locator('#layer').inputValue(),'floor');
await v2.locator('#layer').selectOption('all');await v2.locator('#status').filter({hasText:'28 component instances · ready'}).waitFor();
await v2.locator('#bays').selectOption('4');await v2.locator('#status').filter({hasText:'262 component instances · ready'}).waitFor();assert.equal(await v2.locator('#assembly-title').textContent(),'4 module open assembly');
await v2.locator('#bays').selectOption('8');await v2.locator('#status').filter({hasText:'574 component instances · ready'}).waitFor();
assert.equal(await v2.locator('canvas').evaluate(c=>c.getContext('webgl').getError()),0);
await v2.locator('#layer').selectOption('floor');await v2.locator('#status').filter({hasText:'8 component instances · ready'}).waitFor();
await v2.locator('#bays').selectOption('4');await v2.locator('#layer').selectOption('all');await v2.locator('#status').filter({hasText:'262 component instances · ready'}).waitFor();
await v2.locator('#explode').fill('50');await v2.locator('#explode').dispatchEvent('input');await v2.locator('#reset').click();
await page.screenshot({path:'studio-v2-desktop.png',fullPage:true});
await page.locator('summary').click();await page.locator('[data-version="v1"]').click();assert.equal(await v1.locator('#model-size').textContent(),size);
await page.setViewportSize({width:390,height:844});await page.locator('summary').click();await page.locator('[data-version="v2"]').click();await page.screenshot({path:'studio-v2-mobile.png',fullPage:true});
await page.locator('summary').click();await page.locator('[data-version="v3"]').click();
const v3=page.frameLocator('#v3');await v3.locator('#status').filter({hasText:'30 cassette instances · geometry ready'}).waitFor();
assert.equal(await v3.locator('iframe').count(),0,'Studio must not embed the System inspector');
assert.equal(await v3.locator('#mode').count(),0);
assert.equal(await v3.locator('#height').count(),0);
assert.equal(await v3.locator('label[for="bays"]').textContent(),await v2.locator('label[for="bays"]').textContent());
assert.deepEqual(await v3.locator('#bays option').evaluateAll(opts=>opts.map(o=>o.value)),await v2.locator('#bays option').evaluateAll(opts=>opts.map(o=>o.value)));
assert.deepEqual(await v3.locator('#layer option').evaluateAll(opts=>opts.map(o=>o.value)),await v2.locator('#layer option').evaluateAll(opts=>opts.map(o=>o.value)));
assert.match(await v3.locator('script[src*="app.js"]').getAttribute('src'), /[?]build=[a-f0-9]{40}$/);
assert.match(await v3.locator('a[href*="/tree/"]').textContent(),/^[a-f0-9]{12}$/);
for(let n=1;n<=8;n++){
 await v3.locator('#bays').selectOption(String(n));
 for(const layer of ['floor','walls','roof','all']){
  await v3.locator('#layer').selectOption(layer);
  const expected=layer==='floor'?n:layer==='walls'?3*n+14:4*n+14;
  await v3.locator('#status').filter({hasText:expected+' cassette instances · geometry ready'}).waitFor();
  const actual=await v3.locator('canvas').evaluate(()=>({items:OBTPStudioV3.items.length,bays:OBTPStudioV3.bays,height:OBTPStudioV3.scene.height,skin:OBTPStudioV3.scene.models.some(m=>m.assets.some(a=>a.material==='plywood'))}));
  assert.deepEqual(actual,{items:expected,bays:n,height:2100,skin:false});
  assert.equal(await v3.locator('#schedule tr td:last-child').evaluateAll(cells=>cells.reduce((n,c)=>n+Number(c.textContent),0)),expected);
 }
}
await v3.locator('#explode').fill('50');await v3.locator('#explode').dispatchEvent('input');
assert.equal(await v3.locator('#amount').textContent(),'50%');
assert.equal(await v3.locator('canvas').evaluate(()=>OBTPStudioV3.renderer.explode),.5);
await v3.locator('#reset').click();assert.equal(await v3.locator('#explode').inputValue(),'0');
assert.equal(await v3.locator('canvas').evaluate(c=>c.getContext('webgl').getError()),0);
assert(await v3.locator('body').evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'v3 mobile overflow');
await page.screenshot({path:'studio-v3-mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1050});
await v3.locator('#bays').selectOption('4');
await page.screenshot({path:'studio-v3-desktop.png',fullPage:true});
await page.locator('summary').click();await page.locator('[data-version="v2"]').click();assert.equal(await v2.locator('#bays').inputValue(),'4');
await page.locator('summary').click();await page.locator('[data-version="v3"]').click();assert.equal(await v3.locator('#bays').inputValue(),'4');
const reportUrl=await v3.locator('a[href$="connections.html"]').evaluate(a=>a.href);
const response=await page.request.get(reportUrl);assert.equal(response.status(),200);assert.match(await response.text(),/WHT/);
assert.deepEqual(errors,[]);console.log('PASS: v1/v2 preserved; Studio-owned v3 controls, 32 cassette configurations, quantities, explode/reset, state, source pin, research, WebGL and mobile overflow; no page errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
